### ISSUE TITLE
修改日历宽度出现问题，

### ISSUE THREAD

**Issue by mapleeeeeee** [lspriv/wx-calendar#88]
在某种使用场景下，日历不需要100vw宽度显示，在调试器里看了下css样式，源码宽度给的100vw。
修改css源码，把100vw改成了100%，宽度随父盒子变化，样式能修改成功。
但是切换月份，月份未改变，选中样式也未进行切换。
 
![宽度修改问题](https://github.com/lspriv/wx-calendar/assets/112382489/1adde0e3-3798-47a1-819e-9a93c5757db1)

切换月份之后，使用bindchange方法打印参数，获取到的参数和点击的参数不一致，甚至会报错
![1706689390359](https://github.com/lspriv/wx-calendar/assets/112382489/41074341-14c9-466f-8420-185584f88448)

**Comment by lspriv** [comment]
收到，明天有事，后天解决

**Comment by lspriv** [comment]
给段代码模拟一下你这个场景，我去复现一下 bug :smile:

**Comment by mapleeeeeee** [comment]
wxml 
 `<view class="wrap">
  <view class="nav">
    左侧导航栏</view>
  <view class="calendar-box">
      日历盒子
      <calendar id="calendar" />
  </view>
</view>`

wxss
`.wrap{
  width: 100vw;
  height: 100vh;
  display: flex;
}
.nav{
  width: 160rpx;
  height: 100%;
  background: pink;
}
.calendar-box{
flex: 1;
background: orange;
}`

.json
`{
  "usingComponents": {
    "calendar": "@lspriv/wx-calendar"
  }
}`

以上代码为demo代码，。
如果出现页面元素挤压是没有修改日历宽度，我改了源码的宽度。
谢谢大佬了
![1706837417556](https://github.com/lspriv/wx-calendar/assets/112382489/983dbc1b-c242-4ed2-af56-0d80901d1309)

**Comment by lspriv** [comment]
包@lspriv/wx-calendar@1.5.4-alpha.0已解决该问题

**Comment by lspriv** [comment]
> [!NOTE] 
> 自定义宽度需要注意以下几点（不需要改源码）

##### 1. 直接设置组件绝对宽度
```html
<calendar style="width: 300rpx;" />
```
##### 2. 当日历组件宽度不是绝对值
```html
<view class="wrap">
  <view class="nav"></view>
  <view class="content">
    <calendar style="width: 100%;" />
  </view>
</view>
```
你需要给日历组件的父组件.content设置宽度如下（不要用flex-grow弹性伸缩了，初始化获取不到正确的自定义宽度）
```css
.wrap {
  width: 100vw;
  display: flex;
}

.nav {
  width: 160rpx;
}

.content {
  width: calc(100% - 160rpx);
}
```

**Comment by lspriv** [comment]
> 包@lspriv/wx-calendar@1.5.4-alpha.0已解决该问题

> [!NOTE] 
> 自定义宽度需要注意以下几点（不需要改源码）

#### 1. 直接设置组件绝对宽度
```html
<calendar style="width: 300rpx;" />
```
#### 2. 或者当日历组件宽度不是绝对值时
```html
<view class="wrap">
  <view class="nav"></view>
  <view class="content">
    <calendar style="width: 100%;" />
  </view>
</view>
```
你需要给日历组件的父组件.content设置宽度如下（不要用flex-grow弹性伸缩了，初始化获取不到正确的自定义宽度）
```css
.wrap {
  width: 100vw;
  display: flex;
}

.nav {
  width: 160rpx;
}

.content {
  width: calc(100% - 160rpx);
}
```
